"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Завантажуємо змінні з файлу .env
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'default-unsafe-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'
X_FRAME_OPTIONS = 'DENY'

ALLOWED_HOSTS = ['bunb.pp.ua', 'www.bunb.pp.ua', '91.98.171.31']
CSRF_TRUSTED_ORIGINS = ['https://bunb.pp.ua', 'https://www.bunb.pp.ua']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'portfolio',
    'diploma',
    'django_cleanup.apps.CleanupConfig',
    'csp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'diploma.backends.EmailOrUsernameModelBackend', # Новий бекенд
    'django.contrib.auth.backends.ModelBackend',    # Стандартний бекенд як резервний
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'diploma.context_processors.sidebar_counters',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'django_project',
        'USER': 'bunb',
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': 'localhost',
        'PORT': '5432',
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'uk-UA'

TIME_ZONE = 'Europe/Kyiv' # Для коректного відображення часу в Україні

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# Каталог, куди збирається статика командою collectstatic:
STATIC_ROOT = '/var/www/django_project/static/'
# Опціонально: папка з вашими вихідними статичними файлами
# STATICFILES_DIRS = [BASE_DIR / 'static_source'] 

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/diploma/'  # Після логіну — на дипломну сторінку
LOGOUT_REDIRECT_URL = '/login'  # Після виходу — на головну

MEDIA_URL = '/media/' # URL для завантажених файлів
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Каталог для збереження завантажених файлів

# Налаштування сесій
SESSION_COOKIE_AGE = 3600  # 1 година
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Сесія закривається при закритті браузера

# Налаштування електронної пошти через Gmail SMTP
LOGIN_URL = reverse_lazy('login')
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nazar.haniuk.dev@gmail.com'  # Ваш Gmail
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')  # Пароль додатка
DEFAULT_FROM_EMAIL = 'Глибина 4.0 <nazar.haniuk.dev@gmail.com>' # Від кого надсилати листи за замовчуванням


# Вказуємо Django, що ми за Cloudflare/Nginx, який вже обробляє HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False

# Забороняємо передавати кукі через незахищений HTTP
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Вирішує W004: Увімкнення HSTS (HTTP Strict Transport Security) 1 year
SECURE_HSTS_SECONDS = 31536000 # 1 year in seconds
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# --- НАЛАШТУВАННЯ CSP ---
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'font-src': (
            "'self'",
            'https://fonts.gstatic.com',
            'https://cdnjs.cloudflare.com'
        ),
        'img-src': ("'self'", 'data:', 'blob:'),
        'script-src': (
            "'self'",
            "'unsafe-eval'",
            "'unsafe-inline'",
            'https://cdnjs.cloudflare.com',
            'https://cdn.jsdelivr.net',
            'https://static.cloudflareinsights.com'
        ),
        'style-src': (
            "'self'",
            "'unsafe-inline'", 
            'https://cdnjs.cloudflare.com',
            'https://fonts.googleapis.com',
            'https://cdn.jsdelivr.net'
        ),
        'connect-src': (
            "'self'",
            'https://cloudflareinsights.com',
            'https://cdn.jsdelivr.net',
        )
    }
}

# --- НАЛАШТУВАННЯ КЕШУВАННЯ ---
# Вкрай важливо для Gunicorn з кількома workers (щоб кеш Карти не розсинхронізовувався)
REDIS_URL = os.getenv('REDIS_URL')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': BASE_DIR / 'django_cache',
        }
    }

# --- ЛОГУВАННЯ ПОМИЛОК В PRODUCTION ---
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django_error.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# Кастомізація адмінки
UNFOLD = {
    "SITE_TITLE": "Глибина 4.0 - Адміністрування",
    "SITE_HEADER": "Глибина 4.0",
    "SITE_ICON": {
        "light": lambda request: "/static/diploma/image/favicon.ico",
        "dark": lambda request: "/static/diploma/image/favicon.ico",
    },
    "COLORS": {
        "primary": {
            "50": "#e3f2fd",
            "100": "#c7e5fc",
            "200": "#8ecbf9",
            "300": "#4dabf7", # Ваш фірмовий блакитний колір
            "400": "#339af0",
            "500": "#228be6",
            "600": "#1c7ed6",
            "700": "#1971c2",
            "800": "#1864ab",
            "900": "#14558f",
        },
    },
}