# Generated by Django 5.2.8 on 2026-02-03 12:10

import diploma.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='По батькові')),
                ('badge_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='№ Жетона')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=diploma.models.employee_photo_path, verbose_name='Фото')),
                ('position', models.CharField(choices=[('GOV', 'Гірник очисного вибою (ГОВ)'), ('PROH', 'Прохідник'), ('MASTER_EXP', 'Майстер-підривник'), ('ELECTRO', 'Гірничий електрослюсар'), ('MASTER', 'Гірничий майстер'), ('DISPATCHER', 'Диспетчер'), ('OTHER', 'Інше')], default='GOV', max_length=20, verbose_name='Посада')),
                ('safety_status', models.CharField(choices=[('OFF_SHIFT', 'Не на зміні'), ('OK', 'У шахті (Норма)'), ('WARNING', 'Попередження'), ('SOS', 'ТРИВОГА (SOS)')], default='OFF_SHIFT', max_length=15, verbose_name='Статус')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MineMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основний горизонт', max_length=100, verbose_name='Назва карти')),
                ('map_data', models.JSONField(default=dict, verbose_name='JSON карти')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True, verbose_name='ID на карті')),
                ('wifi_bssid', models.CharField(blank=True, help_text='Формат: AA:BB:CC:11:22:33', max_length=17, null=True, unique=True, verbose_name='MAC (BSSID)')),
                ('x', models.FloatField(verbose_name='X')),
                ('y', models.FloatField(verbose_name='Y')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('map_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploma.minemap', verbose_name='Карта')),
            ],
        ),
        migrations.CreateModel(
            name='MinerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True, verbose_name='MAC пристрою')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Інв. номер')),
                ('firmware_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Прошивка')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='diploma.employee', verbose_name='Видано')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location_label', models.CharField(max_length=100, verbose_name='Місце')),
                ('reason', models.CharField(max_length=50, verbose_name='Причина')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploma.minerdevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploma.employee')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wifi_signal_strength', models.IntegerField(default=0, verbose_name='RSSI')),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('gas_level', models.IntegerField(default=0, verbose_name='Gas PPM')),
                ('battery_level', models.IntegerField(default=100)),
                ('is_moving', models.BooleanField(default=True)),
                ('is_sos', models.BooleanField(default=False)),
                ('sos_reason', models.CharField(default='NONE', max_length=50)),
                ('connected_repeater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diploma.infrastructuredevice')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='diploma.minerdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=diploma.models.user_profile_photo_path)),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
