# Generated by Django 5.2.8 on 2026-02-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='badge_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='№ Жетона'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('GOV', 'Гірник (ГОВ)'), ('PROH', 'Прохідник'), ('MECH', 'Механік'), ('ITP', 'Інженер (ІТП)'), ('DISP', 'Диспетчер')], default='GOV', max_length=20, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='infrastructuredevice',
            name='wifi_bssid',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='MAC (BSSID)'),
        ),
        migrations.AlterField(
            model_name='minerdevice',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Інв. номер'),
        ),
        migrations.AlterField(
            model_name='minerdevice',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True, verbose_name='MAC (ESP32)'),
        ),
    ]
