# Generated by Django 5.2.8 on 2026-01-21 13:07

import diploma.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва типу')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='minemap',
            name='map_data',
            field=models.JSONField(default=dict, verbose_name='Дані карти (JSON з застосунку)'),
        ),
        migrations.AlterField(
            model_name='minemap',
            name='name',
            field=models.CharField(default='Mine Map', max_length=100, verbose_name='Назва карти'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('rfid_tag', models.CharField(max_length=50, unique=True, verbose_name='RFID/NFC Мітка')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=diploma.models.employee_photo_path, verbose_name='Фото')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('current_heart_rate', models.IntegerField(default=0)),
                ('current_battery_level', models.FloatField(default=100.0)),
                ('is_sos_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('OK', 'Робочий'), ('REPAIR', 'В ремонті'), ('LOST', 'Втрачено')], default='OK', max_length=10)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploma.equipmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploma.employee')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploma.equipmentunit')),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True, verbose_name='ID Пристрою (з MineCAD)')),
                ('device_type', models.CharField(choices=[('WIFI_REP', 'WiFi Repeater (ESP32)'), ('ENV_SENS', 'Environmental Sensor'), ('GATEWAY', 'Gateway')], default='WIFI_REP', max_length=20)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'В мережі'), ('OFFLINE', 'Не відповідає'), ('MAINTENANCE', 'На обслуговуванні'), ('ERROR', 'Помилка')], default='OFFLINE', max_length=20)),
                ('last_ping', models.DateTimeField(blank=True, null=True, verbose_name="Останній зв'язок")),
                ('map_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='diploma.minemap')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('INFO', 'Інформація'), ('WARNING', 'Попередження'), ('CRITICAL', 'КРИТИЧНО (SOS)')], max_length=10)),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Вирішено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diploma.employee')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diploma.infrastructuredevice')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('body_temp', models.FloatField(blank=True, null=True)),
                ('battery_level', models.FloatField()),
                ('is_sos', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploma.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='diploma_tel_employe_87c564_idx')],
            },
        ),
    ]
