# Generated by Django 5.2.6 on 2025-09-29 14:16

import diploma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Біографія'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=diploma.models.user_profile_photo_path, verbose_name='Фото профілю'),
        ),
    ]
