# Generated by Django 5.2.8 on 2026-02-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0002_alter_employee_badge_number_alter_employee_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('GOV', 'Гірник очисного вибою (ГОВ)'), ('PROH', 'Прохідник'), ('EXPLODER', 'Майстер підривнки'), ('MASTER', 'Гірничий майстер'), ('ELECTRO', 'Гірничий електрослюсар'), ('DISP', 'Диспетчер')], default='GOV', max_length=20, verbose_name='Посада'),
        ),
    ]
