# Generated by Django 5.2.8 on 2026-02-08 13:34

import diploma.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0003_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='minerdevice',
            name='is_static',
            field=models.BooleanField(default=False, verbose_name='Стаціонарний (на стіні)?'),
        ),
        migrations.AddField(
            model_name='minerdevice',
            name='static_x',
            field=models.FloatField(blank=True, null=True, verbose_name='X (якщо стаціонарний)'),
        ),
        migrations.AddField(
            model_name='minerdevice',
            name='static_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Y (якщо стаціонарний)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Макс. розмір 5 МБ. Фото буде автоматично стиснуто.', null=True, upload_to=diploma.models.employee_photo_path, validators=[diploma.models.validate_image_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('GOV', 'Гірник очисного вибою (ГОВ)'), ('PROH', 'Прохідник'), ('EXPLODER', 'Майстер підривник'), ('MASTER', 'Гірничий майстер'), ('ELECTRO', 'Гірничий електрослюсар'), ('DISP', 'Диспетчер')], default='GOV', max_length=20, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='minerdevice',
            name='assigned_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='diploma.employee', verbose_name='Видано (кому)'),
        ),
    ]
