# Generated by Django 5.2.8 on 2026-02-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0004_minerdevice_is_static_minerdevice_static_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityalert',
            name='rescue_notes',
            field=models.TextField(blank=True, verbose_name='Нотатки диспетчера / Вжиті заходи'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='status',
            field=models.CharField(choices=[('NEW', '🔴 Нова (Необроблена)'), ('IN_PROGRESS', '🟡 В процесі порятунку'), ('RESOLVED', '🟢 Вирішено (Безпечно)')], default='NEW', max_length=20, verbose_name='Статус обробки'),
        ),
    ]
