# Generated by Django 5.2.8 on 2026-02-22 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0005_securityalert_rescue_notes_securityalert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityalert',
            name='connected_repeater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diploma.infrastructuredevice', verbose_name='Найближчий репітер'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='location_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місце'),
        ),
    ]
