# Generated by Django 5.2.8 on 2026-03-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0006_securityalert_connected_repeater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructuredevice',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=64, verbose_name='Пароль мережі (якщо є)'),
        ),
        migrations.AddField(
            model_name='infrastructuredevice',
            name='wifi_ssid',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Саме цю назву шукатиме пристрій в ефірі.', max_length=32, verbose_name='Назва мережі (SSID)'),
        ),
    ]
