# Generated by Django 5.2.8 on 2026-03-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0007_infrastructuredevice_wifi_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityalert',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='telemetrylog',
            name='sos_reason',
            field=models.CharField(default='NONE', max_length=255),
        ),
    ]
