# Generated by Django 5.2.8 on 2026-04-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0008_alter_securityalert_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='Версія прошивки (напр. 1.0.1)')),
                ('binary_file', models.FileField(upload_to='firmwares/', verbose_name='Файл прошивки (.bin)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна (роздавати пристроям)')),
            ],
            options={
                'verbose_name': 'Оновлення прошивки',
                'verbose_name_plural': 'Оновлення прошивок',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
