# Generated by Django 5.2.8 on 2026-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0009_firmwareupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmwareupdate',
            name='binary_file',
            field=models.FileField(upload_to='firmwares_esp/', verbose_name='Файл прошивки (.bin)'),
        ),
    ]
