# Generated by Django 5.2.8 on 2026-04-02 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0010_alter_firmwareupdate_binary_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Версія, що встановлювалась')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Помилка/Деталі')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час спроби')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_logs', to='diploma.minerdevice', verbose_name='Пристрій')),
            ],
            options={
                'verbose_name': 'Лог оновлення (OTA)',
                'verbose_name_plural': 'Логи оновлень (OTA)',
                'ordering': ['-timestamp'],
            },
        ),
    ]
