# Generated by Django 5.2.8 on 2026-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0011_otalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwareupdate',
            name='target_devices',
            field=models.ManyToManyField(blank=True, help_text='Якщо вибрано пристрої, оновлення отримають ТІЛЬКИ вони. Якщо пусто — отримають усі.', to='diploma.minerdevice', verbose_name='Цільові пристрої'),
        ),
    ]
