# Generated by Django 5.2.8 on 2026-04-02 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0012_firmwareupdate_target_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwareupdate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис / Причина оновлення'),
        ),
        migrations.AlterField(
            model_name='firmwareupdate',
            name='version',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Версія має бути у форматі X.Y.Z (тільки цифри та крапки, наприклад: 1.0.0 або 2.1.15)', regex='^\\d+\\.\\d+\\.\\d+$')], verbose_name='Версія прошивки (напр. 1.0.1)'),
        ),
    ]
