# Generated by Django 5.2.8 on 2026-04-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0013_firmwareupdate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrylog',
            name='gas_level',
            field=models.FloatField(default=0, verbose_name='Gas % LEL'),
        ),
        migrations.AlterField(
            model_name='telemetrylog',
            name='is_sos',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='telemetrylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='telemetrylog',
            index=models.Index(fields=['device', '-timestamp'], name='diploma_tel_device__1f492e_idx'),
        ),
    ]
