# Generated by Django 5.2.8 on 2026-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0014_alter_telemetrylog_gas_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityalert',
            name='status',
            field=models.CharField(choices=[('NEW', '🔴 Нова (Необроблена)'), ('IN_PROGRESS', '🟡 В процесі порятунку'), ('WARNING', '🟠 Попередження (Системне)'), ('RESOLVED', '🟢 Вирішено (Безпечно)')], default='NEW', max_length=20, verbose_name='Статус обробки'),
        ),
    ]
