# Generated by Django 5.2.8 on 2026-04-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0015_alter_securityalert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityalert',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diploma.employee'),
        ),
    ]
