# Generated by Django 5.2.8 on 2026-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0016_alter_securityalert_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='minerdevice',
            name='pending_reboot',
            field=models.BooleanField(default=False, verbose_name='Очікує перезавантаження'),
        ),
    ]
