# Generated by Django 5.2.8 on 2026-04-16 09:48

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0017_minerdevice_pending_reboot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='telemetrylog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='diploma_tel_timesta_c51908_brin'),
        ),
    ]
