# Generated by Django 5.2.8 on 2026-04-23 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0019_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmwareupdate',
            name='binary_file',
            field=models.FileField(upload_to='firmwares_esp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bin'])], verbose_name='Файл прошивки (.bin)'),
        ),
    ]
