# Generated by Django 5.2.8 on 2026-04-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0020_alter_firmwareupdate_binary_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('GOV', 'Гірник очисного вибою (ГОВ)'), ('PROH', 'Прохідник'), ('MASTER_EXP', 'Майстер-підривник'), ('MASTER', 'Гірничий майстер'), ('ELECTRO', 'Гірничий електрослюсар'), ('DISPATCHER', 'Диспетчер')], default='GOV', max_length=20, verbose_name='Посада'),
        ),
    ]
