# Generated by Django 5.2.8 on 2026-05-10 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0021_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_time', models.TimeField(default=datetime.time(3, 20), verbose_name='Час щоденної архівації')),
                ('archive_older_than_days', models.IntegerField(default=30, verbose_name='Архівувати дані старші за (днів)')),
                ('keep_archives_count', models.IntegerField(default=180, verbose_name='Кількість архівів для зберігання')),
                ('last_archive_run', models.DateField(blank=True, null=True, verbose_name='Остання успішна архівація')),
            ],
            options={
                'verbose_name': 'Системні налаштування',
                'verbose_name_plural': 'Системні налаштування',
            },
        ),
    ]
