# Generated by Django 5.2.8 on 2026-06-05 09:12

import diploma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0022_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Макс. розмір 50 МБ. Фото буде автоматично стиснуто.', null=True, upload_to=diploma.models.employee_photo_path, validators=[diploma.models.validate_image_size], verbose_name='Фото'),
        ),
    ]
