# Generated by Django 5.2.8 on 2026-01-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True, verbose_name="URL ідентифікатор (напр. 'web')")),
                ('icon_class', models.CharField(default='fas fa-code', max_length=50, verbose_name='FontAwesome іконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок відображення')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва проєкту')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Зображення/Скріншот')),
                ('tech_stack', models.CharField(help_text='Python, Django, SQL', max_length=200, verbose_name='Технології (через кому)')),
                ('github_link', models.URLField(blank=True, verbose_name='GitHub')),
                ('demo_link', models.URLField(blank=True, verbose_name='Demo/Live/Sketchfab')),
                ('is_completed', models.BooleanField(default=True, verbose_name='Завершено?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Проєкт',
                'verbose_name_plural': 'Проєкти',
                'ordering': ['-created_at'],
            },
        ),
    ]
