# Generated by Django 5.2.8 on 2026-01-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(default='fas fa-code', help_text='Наприклад: fas fa-mobile-alt', max_length=50, verbose_name='FontAwesome іконка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, verbose_name='Demo/Live Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, verbose_name='GitHub Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Зображення (скріншот/рендер)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Напр: Python, Django, SQL', max_length=200, verbose_name='Технології (через кому)'),
        ),
    ]
